baseURL = "http://zebraprank.com/"
languageCode = "en-us"
title = "The Zebra Prank - We wrapped our parents car!! by Dylan and Harper Reed"
theme = "harperrules-single-hugo"
publishDir = "docs"

[params]
  ga_id = "UA-70650-71"

[Permalinks]
page= "/:filename/"
