baseURL = "http://zebraprank.com/"
languageCode = "en-us"
title = "The Zebra Prank - We wrapped our parents car!! by Dylan and Harper Reed"
theme = "harperrules-single"
publishDir = "docs"

[Permalinks]
page= "/:filename/"
